#!/bin/sh
set -e
#. /usr/share/debconf/confmodule

RELEASE=`lsb_release -cs`
ppalist="awn-testing bisigi blueman breathe capricorn-lyx chromium-daily c-korn-vlc clutter-edgers compiz do-core exaile-devel firerabbit geany gmchess gnome-colors gnome-games-experimental gnome-terminator gnote-stable gscrot-shutter gstreamer gwibber-daily ibus-dev kubuntu-updates liferea markuz matthaeus123-gimp midori moblin-compatibilty mono-edge moovida mozilla-security pidgin rvm specto sudbury telepathy tualatrix ubuntu-x vicox webkit xbmc-linux"
onlist="awn-testing bisigi blueman breathe-dev chromium-daily do-core exaile-devel gmchess geany-dev gnome-colors-packagers gnome-terminator gnote gwibber-daily kubuntu-ppa liferea markuz midori pidgin-developers shutter specto sudbury-team telepathy team-xbmc tualatrix ubuntu-mozilla-security webkit-team wine-cn"
specialon="c-korn/vlc matthaeus123/mrw-gimp-svn njpatel/clutter-edgers"
offlist="compiz firerabbit gnome-games-experimental gstreamer-developers moblin mono-edge rvm vicox ubuntu-x-swat vicox xorg-edgers"

if [ -x /usr/bin/apt-key ]; then
    /usr/bin/apt-key list > /usr/share/ubuntucn-repo/origkey.list
    /usr/bin/apt-key add /usr/share/keyrings/ubuntucn-repo/ubuntucn-keyring.asc > /dev/null;
    /usr/bin/apt-key add /usr/share/keyrings/ubuntucn-repo/medibuntu-keyring.asc > /dev/null;
    for tmp in $ppalist; do
        /usr/bin/apt-key add /usr/share/keyrings/ubuntucn-repo/ppa/${tmp}.asc > /dev/null
    done
fi

if [ -L /etc/apt/sources.list.d/ubuntucn.list ]; then
   rm -f /etc/apt/sources.list.d/ubuntucn.list
fi

setmirror="mirrors.sohu.com/ubuntu-cn"

while true; do
	printf "Which mirror do you want to choose? Choose a number or press any other key to accept default.\n 1 SOHU mirror(default)\n 2 CN99/163 mirror\n 3 SRT mirror\n 4 LUPA mirror\n 5 UbuntuCN archive\n";
	read input;
	case $input in
		1) printf "You have chosen SOHU mirror.\n"
			setmirror="mirrors.sohu.com/ubuntu-cn"
			break;;
		2) printf "You have chosen CN99/163 mirror.\n"
			setmirror="mirrors.163.com/ubuntu-cn"
			break;;
		3) printf "You have chosen SRT mirror.\n"
			setmirror="ubuntu.srt.cn/ubuntu-cn"
			break;;
		4) printf "You have chosen LUPA mirror.\n"
			setmirror="mirror.lupaworld.com/ubuntu/ubuntu-cn"
			break;;
		5) printf "You have chosen UbuntuCN archive.\n"
			setmirror="archive.ubuntu.org.cn/ubuntu-cn"
			break;;
		*) printf "Default to SOHU mirror."
			setmirror="mirrors.sohu.com/ubuntu-cn"
			break;;
	esac
done

if [ ! -e /etc/apt/sources.list.d/ubuntucn.list ]; then

	echo "deb http://${setmirror}/medibuntu/ ${RELEASE} free non-free" >> /etc/apt/sources.list.d/ubuntucn.list
	echo "deb http://${setmirror}/ubuntu-china-repo/ppa/ubuntu/ ${RELEASE} main" >> /etc/apt/sources.list.d/ubuntucn.list
	echo "deb http://${setmirror}/ibus-dev/ibus-1.2-${RELEASE}/ubuntu/ ${RELEASE} main" >> /etc/apt/sources.list.d/ubuntucn.list
	for list in ${onlist}; do
		echo "deb http://${setmirror}/${list}/ppa/ubuntu/ ${RELEASE} main" >> /etc/apt/sources.list.d/ubuntucn.list;
	done
	for list in ${offlist}; do
		echo "#deb http://${setmirror}/${list}/ppa/ubuntu/ ${RELEASE} main" >> /etc/apt/sources.list.d/ubuntucn.list;
	done

fi

printf "Please reload your software information by \`sudo aptitude update' or by synaptic.\n"
